#NAME: Matei Lupu
#ID: 504798407
#EMAIL: mateilupu20@g.ucla.edu

.SILENT:

default:
	gcc -Wall -Wextra -g -o lab1a lab1a.c
clean:
	rm -r lab1a-504798407.tar.gz lab1a 
dist:
	tar -czvf lab1a-504798407.tar.gz lab1a.c README Makefile

